#!/usr/bin/env ansible-playbook
---
- name: Configure webserver with nginx
  hosts: webservers
  become: true

  tasks:
    - name: install nginx
      apt:
        name: nginx
        update_cache: true

    - name: copy nginx config file
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: 0640

    - name: enable configuration
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: copy index.html
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0640

    - name: restart nginx
      service:
        name: nginx
        state: restarted
...
