#!/usr/bin/env ansible-playbook
---
- name: Configure webserver with nginx
  hosts: webservers
  become: true

  tasks:
    - name: install nginx
      package:
        name: nginx
        update_cache: true

    - name: copy nginx config file
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default

    - name: copy index.html
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: restart nginx
      service:
        name: nginx
        state: restarted
...
