#!/usr/bin/env ansible-playbook
---
- name: Configure webserver with Nginx and TLS
  hosts: webservers
  become: true
  gather_facts: false

  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost

  tasks:
    - name: install nginx
      package:
        name: nginx
        update_cache: true

    - name: create directories for TLS certificates
      file:
        path: /etc/nginx/ssl
        state: directory
        mode: 0750

    - name: copy TLS key
      copy:
        src: nginx.key
        dest: "{{ key_file }}"
        mode: 0600

    - name: copy TLS certificate
      copy:
        src: nginx.crt
        dest: "{{ cert_file }}"
        mode: 0644

    - name: install nginx config template
      template:
        src: nginx.conf.j2
        dest: "{{ conf_file }}"
        mode: 0644

    - name: enable configuration
      file:
        dest: /etc/nginx/sites-enabled/default
        src: "{{ conf_file }}"
        state: link

    - name: install home page
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: "test it! https://localhost:8443/index.html"
      delegate_to: localhost
      become: false
      uri:
        url: 'https://localhost:8443/index.html'
        validate_certs: false
        return_content: true
      register: this
      failed_when: "'Running on ' not in this.content"
      tags:
        - test

...
