#!/usr/bin/env ansible-playbook
---
- name: Configure
  hosts: vagrant
  become: true

  tasks:
    - name: copy config file
      copy:
        content: "myvar: {{ myvar }}"
        dest: /etc/my_var

...
